// BATB Icon constants — emoji + labels for consistent UI
export const ICONS = {
  rose: '🌹',
  theater: '🎭',
  check: '✓',
  pending: '⏳',
  lock: '🔒',
  dance: '🎵',
  vocal: '🎤',
  callback: '⭐',
  calendar: '📅',
  clipboard: '📋',
  ticket: '🎫',
  photo: '📷',
  person: '👤',
  people: '👥',
  chart: '📊',
  mail: '✉️',
  warning: '⚠️',
  sparkle: '✨',
  close: '✕',
  menu: '☰',
  home: '🏠',
  arrow: '→',
};
